# Generated by Django 5.1.3 on 2024-12-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='slides/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the slide in the carousel')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
