# Generated by Django 5.1.3 on 2024-12-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='is_encadrant',
            field=models.BooleanField(default=False, help_text='Designates whether this user is an encadrant.'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_enseignant',
            field=models.BooleanField(default=False, help_text='Designates whether this user is an enseignant.'),
        ),
    ]
