# Generated by Django 5.1.3 on 2024-12-10 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ens', '0003_utilisateur_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='filiere',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ens.filiere'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='groupe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ens.groupe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('etudiant', 'module')},
        ),
    ]
