# Generated by Django 5.1.3 on 2024-12-10 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ens', '0004_note_filiere_note_groupe_alter_utilisateur_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='filiere',
        ),
        migrations.RemoveField(
            model_name='note',
            name='groupe',
        ),
    ]
