# Generated by Django 5.1.3 on 2024-12-10 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ens', '0006_note_filiere_note_groupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='filiere',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ens.filiere'),
        ),
        migrations.AlterField(
            model_name='note',
            name='groupe',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ens.groupe'),
        ),
    ]
