# Generated by Django 5.1.3 on 2024-12-10 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ens', '0007_alter_note_filiere_alter_note_groupe'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='note',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='note',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ens.filiere'),
        ),
        migrations.AlterField(
            model_name='note',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ens.groupe'),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(fields=('etudiant', 'module'), name='unique_note_per_etudiant_module'),
        ),
    ]
