# Generated by Django 5.1.3 on 2024-12-10 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ens', '0008_alter_note_unique_together_alter_note_filiere_and_more'),
    ]

    operations = [
    ]
