# Generated by Django 5.1.3 on 2024-12-10 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ens', '0009_auto_20241210_2031'),
    ]

    operations = [
    ]
