# Generated by Django 5.1.3 on 2024-12-10 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ens', '0010_auto_20241210_2035'),
    ]

    operations = [
    ]
