# Generated by Django 5.1.3 on 2024-12-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ens', '0015_remove_note_filiere_remove_note_groupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='password',
            field=models.CharField(default='qaZFDm5a', max_length=128),
        ),
    ]
