# Generated by Django 5.1.3 on 2024-12-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ens', '0019_alter_etudiant_image_alter_etudiant_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='password',
            field=models.CharField(default='cl74ziTT', max_length=128),
        ),
    ]
