# Generated by Django 5.1.3 on 2024-12-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ens', '0021_alter_etudiant_image_alter_etudiant_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/Assets/profiles/'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='password',
            field=models.CharField(default='n0k8H4Ap', max_length=128),
        ),
    ]
